ath9k: rename htc symbols to avoid conflicts with qca-wifi-host-cmn
Error:
ld.lld: error: duplicate symbol: htc_connect_service
>>> defined in built-in.o(drivers/net/wireless/ath/ath9k/htc_hst.o)
>>> defined in built-in.o(drivers/staging/qca-wifi-host-cmn/htc/htc_services.o)

ld.lld: error: duplicate symbol: htc_start
>>> defined in built-in.o(drivers/net/wireless/ath/ath9k/htc_hst.o)
>>> defined in built-in.o(drivers/staging/qca-wifi-host-cmn/htc/htc.o)

ld.lld: error: duplicate symbol: htc_stop
>>> defined in built-in.o(drivers/net/wireless/ath/ath9k/htc_hst.o)
>>> defined in built-in.o(drivers/staging/qca-wifi-host-cmn/htc/htc.o)
--------------------
Solution:
renamed the symbols htc_connect_service, htc_start, and htc_stop in the ath9k driver to `htc_connect_service_htc`, `htc_start_htc`, and `htc_stop_htc` respectively.

This resolves duplicate symbol errors when building with the qca-wifi-host-cmn driver.

Signed-off-by: 明 <akariondev@gmail.com>
Signed-off-by: Akari <barryofc11@gmail.com>